### ISSUE TITLE
Thank you 👋

### ISSUE THREAD

**Issue by kentcdodds** [szarouski/lerna-wizard#15]
Hey @szarouski! I just discovered this tool and I love it! I noticed your thank you in the README and just had to say Thank YOU! :)

**Comment by kentcdodds** [comment]
Seriously, it's helping me learn lerna better. I've been stuck for a while, but this is really helpful :)

**Comment by webuniverseio** [comment]
@kentcdodds thanks for kind words, this kind of feedback is very important to me. The tool might be a little bit out of date, but I'm really excited that it helped you! I love to give back to community and now I'm more determined than ever to do it more regularly. Thanks for inspiration again 👋❤️
